### ISSUE TITLE
rtMidi Alsa Bug

### ISSUE THREAD

**Issue by aspeteRakete** [danomatika/ofxMidi#19]
Hi there,
I recently noticed a Bug in the Alsa Implementation of rtMidi. When opening more than one input Port of the same device (in my case two Launchpads, or two Input Ports of an MPD32), the Inputs are not always send to the right object.
From time to time I get:
`MidiInAlsa::alsaMidiHandler: unknown MIDI input error!
`
which in fact is an "-EAGAIN" return of Alsa. I think this means, that there is no midi data to be received, meaning, that when an midi event occurs both objects, which are registered with a callback receive the event, regardless if its the right port or not. One of them is faster in reading this out and the others gets this error.
Has anyone experienced the same issue, or can reproduce this?

**Comment by danomatika** [comment]
Does this issue still happen? I imagine it's been fixed in newer versions of RtMidi.

**Comment by vsoft** [comment]
Sorry, I have no idea. Didn't use this project through all these years.
