### ISSUE TITLE
open port by name on windows

### ISSUE THREAD

**Issue by ddiakopoulos** [danomatika/ofxMidi#21]
Didn't have a chance to dig into this, but on Windows 7 I couldn't get ports to be opened by their name.

bool ofxRtMidiOut::openPort(string deviceName) 

The equality operator was failing on the string comparison in this method. My hacked fix was to convert them to c style strings and use strcmp.

**Comment by danomatika** [comment]
Try updating RTMidi.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by moebiussurfing** [comment]
ok @danomatika, thanks
but the current RtMidi version is the same 3.0.0 (http://www.music.mcgill.ca/~gary/rtmidi/) than the one is inluded in your repo...
Do you mean to edit myself the RtMidi source or to use an unstable branch?

**Comment by moebiussurfing** [comment]
I cloned the repo https://github.com/thestk/rtmidi, and replaced the \openframeworks\addons\ofxMidi\libs\rtmidi
content files.
It compiles. I'll if still working my app; and I'll post some report.
thanks @danomatika !

**Comment by moebiussurfing** [comment]
Hmmm nope.  doesn't works like that, Maybe I should compile the sources, to modificate the ofxMidi or something...


```
MidiOutDummy: This class provides no functionality.


MidiInDummy: This class provides no functionality.


MidiOutDummy: This class provides no functionality.


MidiInDummy: This class provides no functionality.
```

**Comment by danomatika** [comment]
RtMidi.h is modified for ofMidi. You need to include ofxMidiConstants.h somewhere around line 150.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by moebiussurfing** [comment]
ok. thanks! it worked adding the line. 
Now using the RtMidi up to date repository
i'll check around the port naming and the port hanging issue. thanks again!

**Comment by moebiussurfing** [comment]
It seems there's some changes to new RtMidi https://github.com/thestk/rtmidi/pull/30
:

```
The API itself is also kept minimal:

getPortCount has its counterpart in getPortList
openPort has been complemented by an implementation that asks the port descriptor to generate a backend object
getPortDescriptor allows to get back the port descriptor from an open virtual port. This is used in the loopback test case to do real MIDI communication (except on Windows that does not support virtual devices).
The new function hasVirtualDevices has been added to query the existence of virtual devices so that the loopback device can shut down gracefully when the backend has no virtual devices.
```

It seems the ports can be handled with something like port description (getPortDescriptor) 
So I imagine there's some need to tweeen around the ofxMidi... 
Btw I don't know the priority of this changes or what other people thinks about the needs.

**Comment by keinstein** [comment]
thestk/rtmidi#30 is not „new“ RtMidi, yet. Currently it is more or less a fork that proposes to solve the problems above. Reviews and discussions about the changes are very welcome.
