### ISSUE TITLE
Song Position Pointer not implemented?

### ISSUE THREAD

**Issue by DamnJack** [danomatika/ofxMidi#26]
SPP message shows status of same, but the value itself is not set; it always returns a 0.  Easy workaround in the meantime -- switch statement on (ofxMidiMessage msg).status:

case MIDI_SONG_POS_POINTER:

            midibeat = msg.bytes[2] << 7 | msg.bytes[1];

            break;

**Comment by danomatika** [comment]
I've added parsing the value for SPP messages into the ofxMidiMessage.value variable. Can you test?
