### ISSUE TITLE
Should a NoteOn with 0 Velocity be treated as a NoteOff?

### ISSUE THREAD

**Issue by aspeteRakete** [danomatika/ofxMidi#29]
From http://www.blitter.com/~russtopia/MIDI/~jglatt/tech/midispec.htm :
'A Note On message that has a velocity of 0 is considered to actually be a Note Off message, and the respective note is therefore released.'

Just wanted to start a discussion on this, since I was a bit confused today (used a piano which showed this behaviour).

**Comment by danomatika** [comment]
The MIDI spec is saying "the receiver should consider NOTEON w/ velocity 0 as a NOTEOFF." I don't think it means "NOTEON's should be translated to NOTEOFF" messages in this case. IMO it's better to leave that up to whoever is writing the message receive logic without any unexpected tricks done within ofxMidi. ofxMidi should only pass messages through.
