### ISSUE TITLE
ios midi over cable with iRig

### ISSUE THREAD

**Issue by joaodafonseca** [danomatika/ofxMidi#32]
Hey guys?

Is it possible to send midi from a ios device over cable using a iRig adapter or similiar? 
Had a look on the ios example and it's only for midi over network.

Thanks in avance,
J

**Comment by danomatika** [comment]
Yes, if the iRig is just a USB MIDI device and doesn't require some special API. USB MIDI devices work fine on the iPad as far as I've tested. The example is not network only and works with them as well.

**Comment by joaodafonseca** [comment]
thanks @danomatika will give it a try :)
