### ISSUE TITLE
Error when compiling in openFrameworks 0.9.3

### ISSUE THREAD

**Issue by Raiuc** [danomatika/ofxMidi#48]
When I try to compile a project updated with project generator I get an error (to add ofxmidi):
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/QuickTime.framework/QuickTime.tbd, missing required architecture x86_64 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/QuickTime.framework/QuickTime.tbd
Undefined symbols for architecture x86_64:
  "ofApp::newMidiMessage(ofxMidiMessage&)", referenced from:
      vtable for ofApp in ofApp.o
  "non-virtual thunk to ofApp::newMidiMessage(ofxMidiMessage&)", referenced from:
      vtable for ofApp in ofApp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The machine is a Mac with OS X 10.11.4, Xcode 7.2.1

**Comment by danomatika** [comment]
See https://github.com/danomatika/ofxMidi/issues/46
