### ISSUE TITLE
Crash when ofxMidi sends messages from multiple thread

### ISSUE THREAD

**Issue by hiroMTB** [danomatika/ofxMidi#54]
ofxMidi always store MIDI message in local variable **message**.

ofxBaseMidiOut.h
```
vector<unsigned char> message;   //< message byte buffer
```

And then call MIDI API (e.g. RtAudio) to actually send data to device.
This design is ok for single thread app.

But If we send MIDI from **multiple thread**, it won't work as expected.
When we send MIDI message simultaneously from different thread, each thread overwrites local vector and create strange data packet. This is typical "data race" situation of multi thread application. To solve this problem, many changes are expected.

On OS X, with RtAudio, API itself looks like multithread friendly, so we can bypass  **message** vector and call API directly like below.

Temporary solution
Sending message directly without copy, via RtMidi native object(tested on OSX, works ok so far)
```
    ofxMidiOut mout;

    void sendNoteOn(int midiCh, int noteNum, int velocity, int duration){
        mout.sendNoteOn(midiCh, noteNum, velocity);  
        std::thread noteOffThread( &MidiSender::sendNoteOff, this, midiCh, noteNum, duration);
        noteOffThread.detach();
    }

    void sendNoteOff(int midiCh, int noteNum, int duration){
        if(duration>0)
            std::this_thread::sleep_for( chrono::microseconds(duration*1000) );

        vector<unsigned char> noteOff;
        noteOff.push_back(MIDI_NOTE_OFF+(midiCh-1));
        noteOff.push_back(noteNum);
        noteOff.push_back(0);
        ofPtr<ofxBaseMidiOut> ofOut = mout.midiOut;
        ofxRtMidiOut * rtOut = static_cast<ofxRtMidiOut*>(ofOut.get());
        rtOut->midiOut.sendMessage(&noteOff);
    }
```

**Comment by Amitsegall** [comment]
Hey ! I would love to implement your solution in my code as well , where should I paste this ? If i understand correctly this will allow me to send multiple notes out with actual note duration right ?
thanks !

**Comment by hiroMTB** [comment]
yes! 
The code above can be used at anywhere in ofApp or your custom class.
You can just call sendNoteOn with duration parameter and it automatically send noteOff later.

Please notice that some of ofxMidi variables are protected or private. (I guess mout.midiOut etc)
And you will see compile error because of it.
You can just move it to public in the meantime.

**Comment by hiroMTB** [comment]
Ah **MidiSender** should be replaced with your class name.

`std::thread noteOffThread( &YourClassNameHere::sendNoteOff, ...`

**Comment by Amitsegall** [comment]
Thanks for writing back quickly - still I can't wrap my head around it (not much of a coder here) - I'm trying to write my own class that will include ofxMidi, and basically my class is your code above, 
i've found the mout.midiOut and set it to public but I still get two errors , one is when setting my class name in the line you mentioned `   std::thread noteOffThread( &MIDIOutClass::sendNoteOff, this, midiCh, noteNum, duration);` where i get "used undeclared identifier 'MIDIOut Class'  ...  and another on the last line `rtOut->midiOut.sendMessage(&noteOff);` which says that midiOut is privet but i can't find it's origin to put it publicly. Thanks for the help !

**Comment by hiroMTB** [comment]
&MIDIOutClass should be the name of your class. which has sendNoteOff function.
And I remember I exposed two or three private variables to public.
Probably it's in the class of ofxMidiOut and ofxBaseMidiOut, will check later.

**Comment by Amitsegall** [comment]
Hey again, 
found all the hidden / private members and moved them to public , not I get the following `_invoke(_VSTD::move(_VSTD::get<0>(__t)), _VSTD::move(_VSTD::get<_Indices>(__t))...);
}
` and it says "attempt to use deleted function" any ideas ?

**Comment by danomatika** [comment]
This should now be fixed as I changed the internal byte buffer to one be used by the MIDI raw byte stream operator. This small caveat has been added to the documentation.

**Comment by Amitsegall** [comment]
Hiroshi's solution works now ! thanks for sorting this out. Polyphony yes ! 
in the midi out example thought if you use 'S' since it is reserved you don't get a note off, but I've locally changed it and used Hiroshi's method to be able to set the duration for the note off. 
Thanks both !!

**Comment by danomatika** [comment]
What do you mean by 'S'?

**Comment by Amitsegall** [comment]
I'm not sure I fully understand what you mean... at the moment i'm running 0.9.8 , and everything is working 👍

**Comment by danomatika** [comment]
Ignore the last post, then. I was making a guess without knowing what platform or OF version you are using.

The way the example's key handling is written, it should only trigger the example sysex sending when you press SHIFT+s. Pressing just 's' should just play a note. What is the issue that you see *exactly*? ie. "When I do ABC, XYZ happens when I thought DEF would."

**Comment by danomatika** [comment]
Nevermind. The issue is that shift+s is handled in keyReleased but not keyPressed. I added a filter now.
