### ISSUE TITLE
receiving chords

### ISSUE THREAD

**Issue by stephanschulz** [danomatika/ofxMidi#57]
I had good success making your add-on work for a project.
But I am struggling understanding how to receive chords due to the serial nature of midi.
Theoretically I should be receiving all the notes of a chord quickly one after the other, but using your input example I only see some of the chord's notes.

Do I have to put the code on it's own thread to get faster read times?

I modified your input example to print in the console when messages change.
https://gist.github.com/stephanschulz/c72930fcd69096b8d1f9e573100a615f

Here is a screenshot using a virtual midi keyboard showing how 3 notes are pressed but only 2 get printed out.
I have noticed this on a real keyboard too.

What am I doing wrong?

<img width="1385" alt="screen shot 2018-05-28 at 9 21 43 pm" src="https://user-images.githubusercontent.com/1054816/40633352-30cf404c-62bd-11e8-966d-3870cf67dc76.png">

**Comment by danomatika** [comment]
Any update on this?

**Comment by stephanschulz** [comment]
sorry did not have time yet. I'm sure you are right and all I need to do was use newMidiMessage()

**Comment by danomatika** [comment]
With ofxMidi 1.1.0, I updated the midiInputExample to queue the incoming messages. This would be easiest way to check for multiple note onset the same time.
