### ISSUE TITLE
midi port hangs using loopMIDI Windows10, forcing reboot to reconnect port

### ISSUE THREAD

**Issue by moebiussurfing** [danomatika/ofxMidi#64]
I am having problems sometimes when using 2 virtual midi in ports (loopMIDI / OF repo / Windows 10).
The midi in port hangs and can't be reconnected restarting the OF app, and I need to reboot the computer. 

No way neither stopping / play the midi port on the loopMIDI gui panel.
It says some error message about "HWmidi-mapper-media-device_blabla" to the console, when I try  connect again to the midi in port (restarting the app)

There's any way to stop/kill the "windows media midi port service" or something to avoid the main reboot?

Both midi in ports are reciving from Ableton. One for midi notes and the other for MTC (using the new updates) I am using only one newMidiMessage shared by the two ports...

**Comment by danomatika** [comment]
I don't have a windows install available right now. I imagine it's an issue with RtMidi and I ask their developers.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Did you get this to work?

>I am using only one newMidiMessage shared by the two ports...

That sounds kind of suspect as the ports might be running on different MIDI threads. If you aren't seeing any random crashes of the entire app, however, then perhaps this is not the issue.

**Comment by moebiussurfing** [comment]
Yes, it worked. Not sure what was my mistake..
