### ISSUE TITLE
midiOutputExample works on iPad Air 2, but not on iPad Air

### ISSUE THREAD

**Issue by Miles-Tone** [danomatika/ofxMidi#66]
When trying to setup a Network Midi Output, it doesn't create, or recognise the network port on iPad Air. The same code works fine on an iPad Air 2

**Comment by Miles-Tone** [comment]
I've actually found that the Audio Midi Settings on the Mac needs to be able to see it otherwise it will not be able to set one up. I don't have time to do a lot of trial and error, but after a bit of wiggling in both the MIDI Network Setup on the Mac, and some building and rebuilding on the iPad, it will jump into life and then continue to work

**Comment by danomatika** [comment]
Did you get this to work?

It could be a weird networking issue as well.

**Comment by Miles-Tone** [comment]
I haven’t been able to, no.
I was using it for an installation, so I just used our teams’ personal iPad Air 2s instead

**Comment by danomatika** [comment]
Closing for now then. Reopen if you ever get back to it.
