### ISSUE TITLE
saving midi file 

### ISSUE THREAD

**Issue by paul-ferragut** [danomatika/ofxMidi#73]
Is it possible to export midi tracks?

Thank you for the addon!

**Comment by danomatika** [comment]
No. It handles MIDI message input and output only. There are a few C and C++ libraries out there for handling MIDI files. You’d basically receive messages, calculate a delta time from the last message, then hand it to the file library.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by paul-ferragut** [comment]
thank you for the quick reply! To send the midi message I would need to open a virtual port I believe? however I can't open a virtual port on Windows with openVirtualPort I have "MidiOutWinNN::openVirtualPort: cannot be implemented in Windows MM MIDI API!"

**Comment by danomatika** [comment]
>To send the midi message I would need to open a virtual port I believe? 

No. You can use open() with a "normal" MIDI port. Virtual ports are not available on Windows as noted by:

* the print you've quoted
* the readme: https://github.com/danomatika/ofxMidi#midi-routing
* the header documentation: https://github.com/danomatika/ofxMidi/blob/master/src/ofxMidiOut.h#L92

As noted in the readme, you can use something which acts as a router between MIDI applications, like loopMIDI.

**Comment by paul-ferragut** [comment]
thank you for your answer
