### ISSUE TITLE
/dev/snd/seq failed: no such file or directory

### ISSUE THREAD

**Issue by batchku** [danomatika/ofxMidi#74]
I have built an OF app with ofxmidi, and when I try to run the app I get this error:
```
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

MidiInAlsa::initialize: error creating ALSA sequencer client object.

terminate called after throwing an instance of 'RtMidiError'
  what():  MidiInAlsa::initialize: error creating ALSA sequencer client object.
Aborted (core dumped)
```

Any ideas what may be causing that @danomatika ?

**Comment by danomatika** [comment]
It's most likely a configuration issue with your system and not something with ofxMidi.

**Comment by danomatika** [comment]
>ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

ie. You might not have the ALSA sequencer module loaded, etc...

**Comment by batchku** [comment]
Thanks @danomatika 
I suspect as much; I have been googling around and not finding the way to do it.
Unfortunately some key ASLA pages are not loading:
https://www.alsa-project.org/~tiwai/lk2k/lk2k.html

Can you point me to where I can learn about how to load asla modules manually?

**Comment by batchku** [comment]
Here is what I see:
```
ali@ali-nono:~$  sudo modprobe snd-seq
modprobe: ERROR: ../libkmod/libkmod-module.c:832 kmod_module_insert_module() could not find module by name='snd_seq'
modprobe: ERROR: could not insert 'snd_seq': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: ../libkmod/libkmod-module.c:979 command_do() Error running install command for snd_seq
modprobe: ERROR: could not insert 'snd_seq': Operation not permitted

```

**Comment by danomatika** [comment]
Closing for now as this is a system config issue and not necessarily an issue with ofxMidi.

**Comment by cyphunk** [comment]
@batchku by chance did you find a solution? I'm testing this addon now on raspberry pi and debugging similar system issues

**Comment by danomatika** [comment]
This might good to add to the readme under the known issues section, if you have time.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by olawalejuwonm** [comment]
@danomatika how did you resolve this issue please?

**Comment by danomatika** [comment]
Judging from batchku's previous post, you just need to reboot after a kernel update for the Alsa dev endpoints to be regenerated.

> Update: I resolved this. If anyone stumbles here, `modprobe snd_seq`. If your pi fails, maybe check that you rebooted the pi since recent kernel update. This was the case with me which I confirmed by checking runtime kernel version `uname` with where snd_req module was found in /lib/modules
> 
> btw helpful for debugging was: `aplay -l` shows the mididevice but `aplaymidi -l` was failing wiht the same snd_seq error

**Comment by olawalejuwonm** [comment]
I'm running on wsl how do I do that?

**Comment by danomatika** [comment]
> I'm running on wsl how do I do that?
> […](#)

Ok, now that we know what system you are on, Google turns up a Github issue on the WSL repo: it's not possible as MIDI hardware is not currently exposed to the Linux layer: https://github.com/Microsoft/WSL/issues/237
