### ISSUE TITLE
Readme: ofxConstants.h or ofxMidiConstants.h?

### ISSUE THREAD

**Issue by okyeron** [danomatika/ofxMidi#77]
Last line of [Readme.md](https://github.com/danomatika/ofxMidi/blob/master/README.md) - is this an error?

`#include "ofxConstants.h"`

Using this I get a compile error looking for `rtmidi.h`

changing to `ofxMidiConstants.h` and I can compile OK.

**Comment by danomatika** [comment]
Yes, it's the wrong file include.

**Comment by danomatika** [comment]
Fixed via fd1794f0949fa94cb8817a6ace6b2bbcad4e4387.
