### ISSUE TITLE
no matching function for call to addListener(ofApp*)

### ISSUE THREAD

**Issue by prismspecs** [danomatika/ofxMidi#81]
I can run the examples just fine, but when I add ofxMidi to my addons.make and put the example code into an existing project I get

```
error: no matching function for call to ‘ofxMidiIn::addListener(ofApp*)’
  midiIn.addListener(this);
```

Any ideas?

**Comment by prismspecs** [comment]
Guess who forgot to extend ofApp with public ofxMidiListener? I did!

**Comment by danomatika** [comment]
This is probably issue 3 or 4 about this. :)
