### ISSUE TITLE
unused variable rate

### ISSUE THREAD

**Issue by dimitre** [danomatika/ofxMidi#83]
I've just noticed this var is unused, so maybe it can be removed. or you intended to use as fps.
https://github.com/danomatika/ofxMidi/blob/56f15102806e8372c144f73559681cbcfbf67cfe/src/ofxMidiTimecode.cpp#L113
Cheers

**Comment by danomatika** [comment]
AH nevermind, it's a double comparison so it's probably been fine.

**Comment by danomatika** [comment]
Removed in latest commit.

**Comment by dimitre** [comment]
Closing here, Thanks for the great addon @danomatika
